---
title: "References"
bibliography: 
    - ref_optimal_control.bib
    - ref_calculus_variations.bib
    - ref_calculus_variations_optimal_control.bib
format:
    html:
        html-math-method: katex
        code-fold: true
execute:
    enabled: false
    warning: false
jupyter: julia-1.10
---

Indirect approach to optimal control is based on *calculus of variations* (and its later extension in the form of *Pontryagin's principle of maximum*). Calculus of variations is an advanced mathematical discipline that requires non-trivial foundations and effort to master. In our course, however, we take the liberty of aiming for intuitive understanding rather than mathematical rigor. At roughly the same level, the calculus of variations is introduced in books on optimal control, such as the classic and affordable [@kirkOptimalControlTheory2004], the popular and online available [@lewisOptimalControl2012], or very accessible and also freely available online [@liberzonCalculusVariationsOptimal2011]. 

With anticipation, we provide here a reference to the paper [@sussmann300YearsOptimal1997], which shows how the celebrated Pontryagin's principle of maximum extends the calculus of variations significantly. But we will only discuss this in the next chapter.

For those interested in a having a standard reference for the calculus of variations, the classic [@gelfandCalculusVariations2000] is recommendable, the more so that it is fairly slim.
