---
title: "What is optimal and robust control?"
bibliography: 
    - ref_optimization.bib
    - ref_optimal_control.bib
    - ref_robust_control.bib
csl: ieee-control-systems.csl
format:
    html     
---

## What is optimal control

What does the adjective "optimal" stand for? According to the authoritative [Oxford English Dictionary (OED)](https://doi.org/10.1093/OED/1089148459), the word is defined as: *best, most favourable, especially under a particular set of circumstance*.

Optimal control is then simply... the best control. 

Whenever optimality of some design is considered, a quantitative measure of the quality of the design must be specified. In control engineering it is typically called *cost function*. It is either provided by the customer, or chosen by the control engineer so that it reflects the customer's requirements. An optimal controller then minimizes this cost. Alternatively, instead of a cost to be minimized, some kind of value to be maximized can be considered. But is a lot more common in control engineering to minimize a cost.  

## Why do we need optimal control

However, the methods of optimal control are not always invoked with the urgent need to minimize some cost. 

## Robust control