---
title: "Course outline"
format:
    html     
---

The course is structured into 14 topics, each of them corresponding to one lecture. The topics are as follows:

- Optimization 
    1. Theory: formulations, conditions, types of problems, optimization modellers, ...
    2. Algorithms: computing derivatives (symbolic, finite difference, autdiff),  gradient, Newton, ..., solvers 
- Discrete-time optimal control
    3. Direct approach (via optimization): on finite horizon, MPC
    4. Indirect approach (via Hamilton equations): finite and infinite horizon, LQR, Riccati equations, ...
    5. Dynamic programming: Bellman's principle, ...
    6. More on MPC: combining direct and indirect approaches and dynamic programming
- Continuous-time optimal control
    7. Indirect approach (via calculus of variations): boundary value problem, Riccati equations, LQR
    8. Indirect approach (via Pontryagin's principle of maximum): time-optimal constrained control
    9. Numerical methods for both direct and indirect approaches: shooting, multiple shooting, collocation
    10. Some extensions of LQ-optimal control: stochastic LQR, LQG, LTR, $\mathcal{H}_2$
- Robust control
    11. Modeling of uncertainty, robustness analysis: small gain theorem, structured singular values
    12. Robust control design: $\mathcal{H}_\infty$-optimal control, $\mu$-synthesis
    13. Analysis of achievable performance
- Other topics
    14. Model order reduction, controller order reduction
