---
title: "References for optimization theory"
bibliography: 
    - ref_optimization.bib
    - ref_numerical_optimal_control.bib
format:
    html:
        html-math-method: katex
        code-fold: true
---

If a single reference book on nonlinear optimization is to be recommended, be it [@nocedalNumericalOptimization2006] that sits on your book shelf. 

If one or two more can still fit, [@bertsekasNonlinearProgramming2016], [@luenbergerLinearNonlinearProgramming2021] are classical comprehensive references on nonlinear programming (the latter covers linear programming too). 

While all the three books are only available for purchase, there is a wealth of resources are freely available online such as the notes [@grosNumericalOptimalControl2022] accompanying a [course on optimal control](https://www.syscop.de/teaching/ss2023/numerical-optimal-control), which do a decent job of introduction to a nonlinear programming, and beautifully typeset modern textbooks [@kochenderferAlgorithmsOptimization2019] and [@martinsEngineeringDesignOptimization2022], the former based on Julia language. 

When restricting to convex optimization, the bible of this field [@boydConvexOptimization2004] is also freely available online. It is a *must-have* for everyone interested in optimization. Another textbook biased towards convex optimization is [@calafioreOptimizationModels2014], which is freely accessible through [its web version](https://inst.eecs.berkeley.edu/~ee127/sp21/livebook/). Yet another advanced and treatment of convex optimization is [@ben-talLecturesModernConvex2023], which is also freely available online. 

Maybe a bit unexpected resources on theory are materials accompanying some optimization software. Partilarly recommendable is [@MOSEKModelingCookbook2024], it is very useful even if you do not indend to use their software.