---
title: Learning goals
format: html
---

## Knowledge (remember and understand)

- Formulate the general problem of calculus of variations. Explain the difference between the *variation* and *differential*.
- Write down the Euler-Lagrange equation and explain its role in optimal control (that it constitutes the first-order necessary condition of optimality for the problem of calculus of variations).
- Give the first-order necessary conditions of optimality for a general (possibly nonlinear) optimal control problem on a fixed and finite time interval. Highlight that it comes in the form of a set of differential and algebraic equations (DAE), together with the boundary conditions that reflect the type of the problem.
- Give the first-order necessary conditions for an optimal control problem on a fixed and finite time horizon with a continous-time LTI system and a quadratic cost - the so-called LQR problem. Discuss the form of boundary conditions if the final state is fixed or free.
- Characterize qualitatively the solution to the LQ-optimal control problem on a fixed and finite time horizon with a fixed final state. Namely, you should emphasize that it is an open-loop control.
- Characterize qualitatively the solution to the LQ-optimal control problem on a fixed and finite time horizon with a free final state. Namely, you should emphasize that it is a proportional time-varying state-feedback control and that the time-varying feedback gains are computed from the solution to the differential Riccati equation.
- Explain the basic facts about LQ-optimal control on an infinite time interval with a free final state. Namely, you should explain that it comes in the form of a proportional state feedback and that the feedback gain can be computed either as the limiting solution to the differential Riccati equation or (and this is preferrable) as a solution to Algebraic Riccati Equation (ARE). The latter option brings in some issues related to existence and uniqueness of a stabilizing controller, which you should discuss.

## Skills (use the knowledge to solve a problem)

- Solve the continuous-time LQR problem using solvers available in your software of choice (Matlab, Julia, Python).