---
title: "References"
bibliography: 
    - ref_optimal_control.bib
    - ref_calculus_variations.bib
    - ref_calculus_variations_optimal_control.bib
csl: ieee-control-systems.csl
format:
    html:
        html-math-method: katex
        code-fold: true
---

Indirect approach to optimal control is based on *calculus of variations* (and its later extension in the form of *Pontryagin's principle of maximum*). Calculus of variations is an advanced mathematical discipline that requires non-trivial foundations and effort to master. In our course, however, we take the liberty of aiming for intuitive understanding rather than mathematical rigor. At roughly the same level, the calculus of variations is introduced in several books on optimal control, such as the affordable and readable @kirkOptimalControlTheory2004, the comprehensible classic @brysonAppliedOptimalControl1975, the popular and online available @lewisOptimalControl2012, or the accessible and yet rigorous (with a draft freely available online) @liberzonCalculusVariationsOptimal2011. 

For those interested in a having a standard reference for the calculus of variations, the classic reference is @gelfandCalculusVariations2000. It is slim, but admittedly rather terse.

With anticipation of what is coming, we provide here a reference to the paper @sussmann300YearsOptimal1997, which shows how the celebrated Pontryagin's principle of maximum extends the calculus of variations significantly. But we will only discuss this in the next chapter.