---
title: Learning goals
format: html
---

## Knowledge (remember and understand)

- Discuss what kind of changes to the necessary conditions of optimality in the form of Euler-Lagrange equations must be made if the final time is relaxed. Consider two cases: first, the state at the final time is free, second, the state at the final time must be on some (hyper)surface.
- Explain the essence of Pontryagin's principle of maximum. Give the full first-order necessary conditions of optimality (for optimal control) using Pontryagin's principle (instead of the equation of stationarity).
- Give (a sketch of) the derivation of time-optimal control for a double integrator with bounds on the control signal – bang-bang control. Discuss the key properties of the resulting controller. Discuss also the practical issues related to implementation. What kind of heuristics could be used to compensate those issues?

## Skills (use the knowledge to solve a problem)

- Design a constrained optimal (possibly minimum-time) controller for a continuous-time systems by invoking Pontryagin's principle of maximum.