---
title: "References"
bibliography: 
    - ref_optimal_control.bib
    - ref_calculus_variations.bib
    - ref_calculus_variations_optimal_control.bib
    - ref_numerical_optimal_control.bib
    - ref_time_optimal_control.bib
csl: ieee-control-systems.csl
---

The content of this lecture is standard and is discussed by a number of books and online resources. When preparing our own material, we took much inspiration from @kirkOptimalControlTheory2004. In particular, we are trying to follow Kirk's way of relating the optimal control problem to the calculus of variations. Although not available online, the printed book is fairly afordable. We also used @liberzonCalculusVariationsOptimal2011, in particular the chapters 3 (application of calculus of variations to general problem of optimal control) and chapter 4 (Pontryagin's principle). Online version of the book is freely available.

Other recommendable classics are @brysonAppliedOptimalControl1975 and @athansOptimalControlIntroduction2006, the former containing solutions to time-optimal control for several other basic linear systems such as harmonic oscillators. The popular @lewisOptimalControl2012 is a bit less detailed when it comes to the topics of this particular chapter/lecture, but it is still recommendable.

We did not even sketch the proof of Pontryagin's principle and we do not command the students to go through the proof elsewhere. Admittedly, the proof is rather challenging. But a motivated student can skim through it, for example in [@liberzonCalculusVariationsOptimal2011, Chapter 4]. Understanding the very statement of the theorem, its roots in calculus of variations, and how it removes the deficiencies of the calculus of variations will suffice for our purposes.

The transition from the calculus of variations to the optimal control, is based on the fundamental observation that the derivative of the dependent variable y'(x) should be treated as and independent input argument of the Hamiltonian function. While this is typically not emphasized in the textbooks, an exceptionally insightful treatment is in the paper @sussmann300YearsOptimal1997, in particular in the section "The first fork in the road: Hamilton" on page 39. We strongly recommend reading at least this first section of the paper.  

The time-optimal control for linear systems, in particular bang-bang control for a double integrator is standard and is described in many textbooks and lecture notes on optimal control, for example in section 4.4.1 and 4.4.2 in @liberzonCalculusVariationsOptimal2011. 

What is often not emphasized in textbooks, however, is the fact that without any modifications, the bang bang control is rather troublesome from an implementation viewpoint – it leads to *chattering*. A dedicated research thread has evolved, driven by the needs of hard disk drive industry, which is called *(a)proximate time-optimal control* (PTOS). Many dozens of papers can be found with this keyword in the title. For instance, @workmanAdaptiveProximateTimeOptimal1987, and @paoProximateTimeoptimalControl1993.

Among numerous other resources available freely online, the lecture notes [@grosNumericalOptimalControl2022, Section 12.3], and @evansIntroductionMathematicalOptimal can also be recommended.