---
title: "References"
bibliography: 
    - ref_numerical_optimal_control.bib
    - ref_optimal_control.bib
    - ref_model_predictive_control.bib
csl: ieee-control-systems.csl
format: html
---

The key concept of this chapter — model predictive control (MPC), aka receding horizon control (RHC) — has been described in a number of dedicated monographs and textbooks. Particularly recommendable are [@rawlingsModelPredictiveControl2017] and [@borrelliPredictiveControlLinear2017]. They are not only reasonably up-to-date, written by leaders in the field, but they are also available online for free.

Some updates as well as additional tutorials are in [@rakovicHandbookModelPredictive2019], which seems to be available to CTU students through the [institutional access](https://ebookcentral.proquest.com/lib/cvut/detail.action?docID=5504961).

There is no shortage of lecture notes and slides as well. Particularly recommendable are the course slides [@bemporadModelPredictiveControl2021a], and [@boydModelPredictiveControl].

Extensions towards nonlinear systems (nonlinear model predictive control, NMPC) are described in [@gruneNonlinearModelPredictive2017], which is also available to CTU students through the [institutional access](https://cvut.summon.serialssolutions.com/#!/search?bookMark=eNqFkUtPwzAQhA0URFr6AzggVb0gDqF-JbGPUJWHVMEFcbUc22lDQ1xsp_x93AZx5biab0a7s0Mwll1YmzbUSgajAbhE8BZBWMx4wVKSEsRTmkNM0_wIDEkcDxM-BglGvEgLhPhJLzBCMUEDkEAUrRnJ6BlIeI6LDDKOz8HY-w8Io5hjWKAETF9s29StkW7yabVpJltndK1CvTMTZdvgbHMBTivZeDMGg-A6MwLvD4u3-VO6fH18nt8tU0lggVla8kqpjLOSxWhNKoxIqaqq1JQZU5WVolrpnGhGFUKGasmqkjIc3UyznOZkBK76YLXrgohNyMauRFyW4XgWwyNw0-vSb8y3X9smeLFrTGntxovY1F8xeWRnPeu3rm5XxomeQlDse93TgojIi4NB7B3XvWPr7FdnfBCHYBW_4mQjFvdzWlDIMxTJ6e-e0svYXS0-bWtXTm7XXmTxEEgy_N8xPxJ1iPU). Alternatively, concise introductions are [@grosLinearNonlinearMPC2020] and [@grosNumericalOptimalControl2020, Chapter 15].

Since MPC essentially boils down to solving optimization problems in real time on some industrial device, the topic of embedded optimization is important. An overview is given in [@ferreauEmbeddedOptimizationMethods2017]. Although some new solvers appeared since its publication, the practical considerations highlighted in the paper are still valid.