---
title: "Numerical solvers for MPC"
format: html
---

## QP solvers suitable for (linear) MPC

The extra features needed for MPC:

- warmstarting requires fesibility of the previous solution. Some methods the iterations may temporarily lose feasibility, which can be a problem if only a fixed number of iterations is allowed (in favor of predictable timing).
- ...

A curated list of QP solvers is maintained at [https://github.com/qpsolvers/qpbenchmark](https://github.com/qpsolvers/qpbenchmark). Below are a few most popular from the open-source domain. Most if not all of them can be interfaced from various programming languages.

- [qpOASES](https://github.com/coin-or/qpOASES)
- [OSQP](https://osqp.org)
- [DAQP](https://github.com/darnstrom/daqp)
- [qpSWIFT](https://github.com/qpSWIFT/qpSWIFT)
- [ProxQP](https://github.com/Simple-Robotics/proxsuite)
- [PiQP](https://github.com/PREDICT-EPFL/piqp)
- [ECOS](https://github.com/embotech/ecos)
- [HPIPM](https://github.com/giaf/hpipm)

## Higher-level tools

- [acados](https://docs.acados.org) – free & open source; interfaces to Octave/Matlab, Python, C++.
- [CasADi](https://web.casadi.org) – free & open source; interfaces to Octave/Matlab, Python, C++.
- [ModelPredictiveControl.jl](https://github.com/JuliaControl/ModelPredictiveControl.jl) – free & open source; Julia.
- [Model Predictive Control Toolbox for Matlab](https://www.mathworks.com/products/model-predictive-control.html) – commercial (by The Mathworks); Matlab; the generated C code follows industrial standards.
- [Multiparametric Toolbox 3 (MPT3)](https://www.mpt3.org) – free & open source; Matlab.
- [Yalmip](https://yalmip.github.io) – free & open source; Matlab.
- [ForcesPro](https://www.embotech.com/softwareproducts/forcespro/overview/) – commercial (by Embotech).