---
title: Rules of the course
format: html
---

## Your studying starts before the lecture

In this course we follow – at least in some weeks – the concept of *flipped learning*. This means that you are expected to study a bit on your own even before the lecture. The study material is made available through this web site. It consists primarily of texts, codes and frequently also videos. At the lecture we will not repeat the introductory material, instead we will discuss it, and focus on the more advanced topics and examples.

## Learning goals

To guide you in your self-study before the lecture, we always provide a set of *learning goals* for the given (weekly) block. These learning goals (also *competences*) are structured into two parts – **knowledge and understanding**, and **problem-solving skills**. These are formulated in a way that guides you while studying. Always start by reading this list and only then proceed to the study material. Then come back to the learning goals and check if you can tick them off.

## Online quizzes

In order to push you gently towards such studying before the lecture, you will be asked to fill in a short online quiz (in [Moodle](https://moodle.fel.cvut.cz)) even before the actual lecture. 

::: {.callout-important}
## Deadlines for online quizzes
The **deadlines** are always set to the very beginning of the lectures, that is, **Wednesday, 11:00 am**.
::: 

These quizzes will not test if you achieved all the learning goals – you are certainly not expected to learn everything by yourself. Typically only some easier learning goals of the "knowledge and understanding" type will be tested.

The role of such quizzes in the overall grading is described later on this page.

## Homework problems

Homework problems are assigned weekly. They are typically related to the "skills" part of the learning goals, and as such they will almost exclusively consist of writing some computer code.

Approximately the second half of each exercise session will always be dedicated to the homework problem(s). Ideally you will be able to solve the problems before leaving the classroom (benefit of the flipped learning). But even if not, you will at least have an opportunity to get started with solving the problem, while taking advantage of having a teaching instructor and other students nearby. 

A challenging – but perhaps rewarding as well – attribute of our programming homework problems is that their solutions are expected to be programmed in Julia language (see [Software for the course](intro_software.qmd)). 

You will be expected to submit the solutions through the [Brute system](https://cw.felk.cvut.cz/brute/), which will give an immediate feedback if the submitted solution is accepted or not (such functionality is not yet available in Moodle, sorry, that is why we are mixing the systems). If the submitted solution is automatically evaluated as incorrect, students can resubmit it (the number of allowed uploads is set reasonably high, but do not treat the system as a *unit testing* framework). 

::: {.callout-important}
### Deadlines for submission of solutions to homework problems
The **deadlines** are always set to **Wednesday**, just before the beginning of the corresponding exercises, e.g., **12:45, 14:30, 16:15**.
:::

## Semestral project

Students aiming at the final grading A must work on one project from our list during the semester (details will be made available shortly after the beginning of the semester). Students with no ambitions for the A grade do not have to work on the projects. 

Although students are encouraged to collaborate, the submitted report must state the names of all the collaborating students.

As an outcome of the project, a short report should be presented to the teacher. Any time before or at their own exam. An ideal format of such report is a git repository within the [FEE Gitlab](https://gitlab.fel.cvut.cz) containing a short text, software code, possibly data sets (from simulations or experiments), and graphs, photos, videos (from experiments).

Its grading is binary –⁠ either it is accepted by the teacher or not. In case the report is not accepted, details will be given and the student can correct/improve/extend the report and resubmit. Note however, that at least one week (5 working days) is needed for the teacher to evaluate the report. Consequently, a report submitted only a few days before the deadline stands no chance to be modified and resubmitted. 

## Grading

### Online quizzes and homework problems 

The primary motivation for introduction of the online quizzes and homework problems is to help your learning process (you receive feedback in real time). Your performance in quizzes and homework problems does not affect the final grade. Feel free to make some mistakes while learning.

However, some thresholds do have to be passed in quizzes and homework problems to earn the credit ("zápočet" in Czech), and to be allowed to take an exam. The bar is not high, but if you are neglecting the quizzes and homework assignments, your passing will be in danger. Namely, **at least 50%** of competences (demonstrated in quizzes and homework problems, satisfying the limit in each) must be provably mastered. 

### Final exam

The final grade will be based on the exam organized at the end of the semester (in the exam period).  The final exam will have both an open-book and closed-book parts. 

The open-book part will test the problem solving skills, and it will be done in the form of a written test. An example test will be made available in advance.

The closed-book part will be done in the form of an oral exam. A few questions from the battery of the online quiz questions will be asked. Their wording will be nearly identical as in the quizzes, but instead of the multiple-choice answers, the students will be asked to provide a short answer by themselves.

### Overall grade

Grading of the two partial exams will be done according to the following standard table, where the percentages refer to the number of maximum points that could be obtained in the given exam.

| Grading | Open-book exam | Closed-book exam |
|---------|----------------|------------------|
| A       | 90 %           | 90 %             |
| B       | 80 %           | 80 %             |
| C       | 70 %           | 70 %             |
| D       | 60 %           | 60 %             |
| E       | 50 %           | 50 %             |
| F       | below 50 %     | below 50 %       |

Ultimately, in order to arrive at the overall final grade (A through F) we take the minimum of the two partial exam grades.

### Role of the semestral project in the grading

While the semestral projects are not mandatory, without them you will not be able to get the highest grade A. On the other hand, if you do the project and your report is accepted, and you pass the exam, the grade you receive in the exam will be automatically improved by one (e.g., from C do B).