---
title: Similar courses at other universities
format: html
---

Below we give a selection of courses on optimal and robust (oftentimes not together) control that are given by excellent instructors at research universities abroad:

- S. Boyd. [EE363 - Linear Dynamical Systems](https://web.stanford.edu/class/ee363/index.html). Stanford. Winter 2008-2009.
- R. D'Andrea. [151-0563-01L – Dynamic Programming and Optimal Control](https://idsc.ethz.ch/education/lectures/optimal-control.html). ETH Zurich. Fall 2024.
- M. Diehl. [Numerical Optimal Control](https://www.syscop.de/teaching/ws2024/numerical-optimal-control). University of Freiburg, Winter semester 2024/2025.
- M. Egerstedt. [ECE6553 - Optimal Control and Optimization](https://ece.gatech.edu/courses/ece6553). Georgia Tech. Spring 2017.
- T. Faulwasser, Y. Jiang. [EE-736 – Control for Dynamic Systems](https://edu.epfl.ch/coursebook/en/optimal-control-for-dynamic-systems-EE-736). EPFL. 2024. 
- A. Hanson. [TSRT08 – Optimal control](https://isy.gitlab-pages.liu.se/rt/en/courses/TSRT08/). Linkoping University. Fall 2024. 
- M. Hovd. Robust control. Norwegian University of Science Technology, Trondheim, Norway.
- J. How. [16323 – Principles of Optimal Control](https://ocw.mit.edu/courses/16-323-principles-of-optimal-control-spring-2008/). MIT. Spring 2008.
- A. Karimi. [Robust control](https://www.epfl.ch/labs/la/page-62809-en-html/). EPFL, Lausanne.
- S. Lall. [Engr210a - Robust Control Analysis and Synthesis](https://lall.stanford.edu/engr210a/). Stanford. Autumn 2001-2002.
- Z. Manchester. [16-745 – Optimal Control and Reinforcement Learning](https://optimalcontrol.ri.cmu.edu/). Carnegie Mellon University. 2025.
- A. Megretski. [6.245 - Multivariable Control Systems](https://ocw.mit.edu/courses/6-245-multivariable-control-systems-spring-2004/). MIT. Spring 2004.
- T. A. E. Oomen, and J.W. van Wingerden. [Design Methods for Control Systems](https://disc.tudelft.nl/wp-content/uploads/2024/09/2025_Design-Methods-for-Control-Systems.pdf). Dutch Institute of Systems and Control (DISC), The Netherlands. 2025.
- M. Pavone, D. Gammelli, D. Morton, M. Foutter. [AA 203 – Optimal and Learning-Based Control](https://stanfordasl.github.io//aa203/sp2324/). Stanford University. Spring 2024.
- A. Rantzer. [Robust Control](https://archive.control.lth.se/Education/DoctorateProgram/robust-control/robust-control-2015.html). Lund University. 2015.
- M. Salapaka. [EE5235/AEM8425 - Robust Control](https://people.ece.umn.edu/~murtis/teaching/EE5235/ee5235.html). University of Minnesota.
- C.W. Scherer. Robust control. TU Delft. Since 2006 not accessible outside TU Delft.
- S. Skogestad. [Multivariable feedback control using frequency-domain methods](https://skoge.folk.ntnu.no/book/course43917.html). Norwegian University of Science Technology, Trondheim, Norway. Replaced by the course given by M. Hovd, last run 1999.

