---
title: Learning goals
format:
    html:
        html-math-method: katex
---

## Knowledge (remember and understand)

- Explain how the peak in the sensitivity and complementary sensitivity functions relate to gain and phase margins.
- Explain the concept of a bandwidth. Shall we define it using the sensitivity or the complementary sensitivity functions?
- Give the two "waterbed effect" integral formulas. You do not have to remember the formulas exactly but at least the essence.
- Give the SISO version of interpolation conditions of internal stability. Namely, assuming that the transfer function of the system vanishes at z in the right half plane of the complex plane, it must hold that $S(z) = 1$. Similarly, for an unstable pole p of the system, it must hold that $T(p) = 1$. 
- Give the lower bound on the peaks in the weighted sensitivity function in presence of poles and/or zeros in the right half plane.
- How does the time delay in the system affects the achievable bandwidth?
- How does the presence of disturbance affect the achievable bandwidth?
- What conditions on system transfer function(s) are imposed by the saturation of actuators? More accurately, under which conditions is it guaranteed that the actuators do not saturate?
- Explain the concept of directionality in MIMO systems.
- Explain the condition number of the matrix of transfer functions. How can it be computed? Perhaps only approximately.
- How does the presence of input multiplicative uncertainty affect the achievable behavior of the closed-loop transfer functions?

## Skills (use the knowledge to solve a problem)

- Analyze the provided linear model of dynamics of the system to be controlled in order to learn the limitations on achievable performance such as bandwidth, resonant peak, steady-state regulation error etc.