---
title: "References"
bibliography: 
    - ref_optimization.bib
    - ref_numerical_optimal_control.bib
csl: ieee-control-systems.csl
format:
    html:
        html-math-method: katex
        code-fold: true
---

If a single reference book on nonlinear optimization is to be recommended, be it [@nocedalNumericalOptimization2006] that sits on your bookshelf. 

If one or two more can still fit, [@bertsekasNonlinearProgramming2016], [@luenbergerLinearNonlinearProgramming2021] are classical comprehensive references on nonlinear programming (the latter covers linear programming too). 

While all the three books are true classics, they are only available for purchase. Fortunately, there is a wealth of resources that are freely available online such as the notes [@grosNumericalOptimalControl2022] accompanying a [course on optimal control](https://www.syscop.de/teaching/ss2023/numerical-optimal-control), which do a decent job of introduction to a nonlinear programming, and beautifully typeset modern textbooks [@kochenderferAlgorithmsOptimization2019] and [@martinsEngineeringDesignOptimization2022]. The former is even based on Julia language, while the latter has also its online [html version](https://mdobook.github.io/html/). Yet another high-quality textbook that is freely available online is [@bierlaireOptimizationPrinciplesAlgorithms2018].

When restricting to convex optimization, the bible of this field [@boydConvexOptimization2004] is also freely available online. It is a *must-have* for everyone interested in optimization. Yet another advanced treatment of convex optimization is [@ben-talLecturesModernConvex2023], which is also freely available online. 

Maybe a bit unexpected resources on the optimization theory are materials accompanying some optimization software. Particularly recommendable is [@MOSEKModelingCookbook2024], it is very useful even if you do not intend to use their software. In particular, their introduction to conic optimization is very well written and easy to follow.

Some practical aspects are discussed in [Guidelines for Numerical Issues](https://www.gurobi.com/documentation/current/refman/guidelines_for_numerical_i.html) for Gurobi Optimizer.