---
title: "Software"
bibliography: 
    - ref_optimal_control.bib
    - ref_robust_control.bib
csl: ieee-control-systems.csl
format:
    html:
        html-math-method: katex
        code-fold: true
        code-summary: "Show the code"
crossref:
  fig-prefix: Fig. 
  eq-prefix: Eq.
engine: julia
---

## Julia

### RobustAndOptimalControl.jl

The main package for robust and optimal control in Julia. Documentation at [RobustAndOptimalControl.jl](https://juliacontrol.github.io/RobustAndOptimalControl.jl/stable/). There is a [dedicated section](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/#H_\\infty-and-H_2-design) in the manual on the $\mathcal H_\infty$ control design.

  - [hinfsynthesize](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.hinfsynthesize-Union{Tuple{ExtendedStateSpace{Continuous,%20T}},%20Tuple{T}}%20where%20T): control design by minimizing the $\mathcal{H}_\infty$ norm of the lower LFT of of the generalized plant with respect to the feedback controller.
  - [hinfpartition](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.hinfpartition-NTuple{4,%20Any}): creates a generalized plant such that the $\mathcal{H}_\infty$-optimal control problem with this plant is equivalent to the mixed-sensitivity problem with the given weighting filters.
  - [partition](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.partition-Tuple%7BAbstractStateSpace%7D): creates a generalized plant from the given state-space model and the specified partition of the input and output channels into exogenous inputs, control inputs, regulated outputs, and measured outputs.
  - [specificationsplot](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.specificationplot): plotting the sensitivity, complementary sensitivity and input sensitivity functions and corresponding weighting filters relevant in the mixed sensitivity design.
  - [glover_mcfarlane](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.glover_mcfarlane): Glover-McFarlane method of robust stabilization of a loop-shaping design based on $\mathcal{H}_\infty$ optimal control.
  - [glover_mcfarlane_2dof](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.glover_mcfarlane_2dof): the same as above, but yielding a two-degree-of-freedom controller.
  - [hanus](https://juliacontrol.github.io/RobustAndOptimalControl.jl/dev/api/#RobustAndOptimalControl.hanus-Tuple{Any}): a technique for antiwindup.

### DyadControlSystems.jl

Documentation at [DyadControlSystems.jl](https://help.juliahub.com/dyad/DyadControlSystems.jl/stable/). This package (formerly named JuliaSimControl as a part of the JuliaSim project) is a part of the [Dyad](https://juliahub.com/products/dyad) project and contains some additional methods for $\mathcal{H}_\infty$ control design. In particular, it implements the LMI-based solver for the general $\mathcal{H}_\infty$ control problem, which relaxes some of the assumptions that the Riccati equation based solver implemented in RobustAndOptimalControl.jl needs. However, the package is not a free software. Documentation at [DyadControlSystems.jl](https://juliacontrol.github.io/DyadControlSystems.jl/dev/).

The package, although free for nonncommercial use, is not available in the public Julia package registry. To install Dyad.jl and DyadControlSystems.jl, you need to follow their [installation instructions](https://help.juliahub.com/dyad/stable/installation.html). 

## Matlab 

### Robust Control Toolbox

- [mixsyn](https://www.mathworks.com/help/robust/ref/dynamicsystem.mixsyn.html): control design by minimizing the $\mathcal{H}_\infty$ norm the the mixed-sensitivity function.
- [hinfsyn](https://www.mathworks.com/help/robust/ref/dynamicsystem.hinfsyn.html): control design by minimizing the $\mathcal{H}_\infty$ norm of a closed-loop transfer function formulated using an LFT.
- [hinfstruct](https://www.mathworks.com/help/robust/ref/dynamicsystem.hinfstruct.html): fixed-structure $\mathcal{H}_\infty$ control design by minimizing the $\mathcal{H}_\infty$ norm of a closed-loop transfer function formulated using an LFT. 
- [ncfsyn](https://www.mathworks.com/help/robust/ref/lti.ncfsyn.html): Glover-McFarlane method of robust stabilization of a loop-shaping design based on $\mathcal{H}_\infty$ optimal control. 
- [musyn](https://www.mathworks.com/help/robust/ref/uss.musyn.html): similar general setup as the hinfsyn method, but it considers a structure in the $\Delta$ term. It is regarded by some as the culmination of the $\mathcal{H}_\infty$ control design methods. The disadvantage is that it is the most computationally intensive of the methods we covered, and the resulting controller is typically of rather high order.

## Python

- [Python Control Systems Library](https://python-control.readthedocs.io/en/latest/index.html)