---
title: "References"
bibliography: 
    - ref_optimal_control.bib
    - ref_robust_control.bib
csl: ieee-control-systems.csl
format:
    html:
        html-math-method: katex
        code-fold: true
        code-summary: "Show the code"
crossref:
  fig-prefix: Fig. 
  eq-prefix: Eq.
engine: julia
---

The literature for $\mathcal H_\infty$ control is essentially identical to the one we gave in the previous chapter on analysis of robustness. In particular, we stick to our primary textbook @skogestadMultivariableFeedbackControl2005, in which the material is discussed in the forty-page Chapter 9 (but not the full chapter needs to be read as it also includes LQG and $\mathcal H_2$ methods, which we have already covered elsewhere). 

Namely, the general $\mathcal H_\infty$ optimal control problem is introduced in sections 9.3.4 and 9.3.6. The interleaved section 9.3.5 covers the mixed sensitivity design procedure. The loop-shaping method is thoroughly explained in 9.3.6. It also contains a detailed discussion of an extension to the 2DOF case, implementation in the observer-state-feedback form, and some sort of antiwindup technique.

While discussing the analysis of robustness in the previous chapter, we omitted a discussion of *structured uncertainties* using the *structured singular values* (SSU, mu, $\mu$). Similarly here we did not delve into the extension of that framework towards control synthesis. Purely because of time constraints. But should you find some time, have a look at section 8.12, which discusses the methodology called $\mu$ synthesis.
