---
title: Learning goals
format:
    html:
        html-math-method: katex
---

## Knowledge (remember and understand)

- Describe the control design procedure called $\mu$-synthesis that aims at achieving robust stability in presence of structured uncertainty. Show how the requirement of robust performance can be included in this robust stabilization framework (the answer: by including an artificial uncertainty block corresponding to performance specs).
- Explain the algorithm called DK-iteration that is used to solve the $\mu$-synthesis problem.
- Discuss the shortcomings of the $\mu$-synthesis procedure (they mostly stem from the *DK-iteration* algorithm). 
- Explain the essence of the $\mathcal H_\infty$ optimization-based *loop-shaping* method. In particular, explain briefly the type of uncertainty against which the controller is designed to be robust. What are the advantages of this method compared the other $\mathcal H_\infty$ optimization-based methods?

## Skills (use the knowledge to solve a problem)

- Design a controller for robust performance using $\mu$-synthesis. 
- Design a robust controller using $\mathcal H_\infty$ optimization-based loop-shaping method. 