---
title: Learning goals
format:
    html:
        html-math-method: katex
---

## Knowledge (remember and understand)

- Give the general optimization criterion for the control-design procedure based on minimizing the $\mathcal H_\infty$-norm of the *mixed sensitivity* function.
- Explain the control design procedure based on minimizing the $\mathcal H_\infty$-norm of the *linear fractional transformation (LFT)* of a *generalized plant* and a stabilizing controller.
- ~~Explain the control design procedure called 𝜇-synthesis and aiming at achieving robust stability in presence of structured uncertainty. Show how the requirement of robust performance can be included in this robust stabilization framework (the answer: by including an artificial uncertainty block corresponding to performance specs).~~ 

## Skills (use the knowledge to solve a problem)

- Design a robust controller by $\mathcal H_\infty$ norm minimization (your task is actually just to formulate the control design problem as the optimization problem, the actual numerical job of optimization can be relegated to an available numerical solver). Namely, you should master the technique of control design by minimizing the $\mathcal H_\infty$ norm of *mixed sensitivity* function but you should also be able to formulate (and use Matlab to solve) the general $\mathcal H_\infty$-optimal control problem. ~~A closely related design procedure that you should master is that of 𝜇 synthesis.~~