---
title: "References"
bibliography:
    - ref_order_reduction.bib
    - ref_optimal_control.bib
format:
    html:
        html-math-method: katex
---

The primary reference for our overview of methods for model and controller order reduction is Chapter 11 in @skogestadMultivariableFeedbackControl2005. For a more detailed introduction, there a few dedicated monographs such as @obinataModelReductionControl2000 and @antoulasApproximationLargeScaleDynamical2005. A short extract from the latter is in @antoulasApproximationLargescaleDynamical2001.

The latter also excels in that it also admits that the topic of reduction of order of mathematical models formatted as state equations is not only relevant for the control systems community but from a number of other engineering and scientific communities as well. After all, mathematical models are not only for model-based control design but for simulation, optimization, and other purposes. For example, the in @tanAdvancedModelOrder2007 they are motivated by fast simulation of VLSI circuits.